# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 286)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(381, 286))
        MainWindow.setMaximumSize(QtCore.QSize(381, 286))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 361, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_output_xlsx = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_output_xlsx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_output_xlsx.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_output_xlsx.setObjectName("frame_output_xlsx")
        self.label_output_xlsx = QtWidgets.QLabel(self.frame_output_xlsx)
        self.label_output_xlsx.setGeometry(QtCore.QRect(6, 10, 341, 20))
        self.label_output_xlsx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_output_xlsx.setObjectName("label_output_xlsx")
        self.name_output_xlsx = QtWidgets.QLabel(self.frame_output_xlsx)
        self.name_output_xlsx.setGeometry(QtCore.QRect(6, 30, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.name_output_xlsx.setFont(font)
        self.name_output_xlsx.setMouseTracking(False)
        self.name_output_xlsx.setAlignment(QtCore.Qt.AlignCenter)
        self.name_output_xlsx.setObjectName("name_output_xlsx")
        self.name_output_xlsx.raise_()
        self.label_output_xlsx.raise_()
        self.gridLayout.addWidget(self.frame_output_xlsx, 1, 0, 1, 2)
        self.frame_grade_csv = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_grade_csv.setAcceptDrops(True)
        self.frame_grade_csv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grade_csv.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_grade_csv.setObjectName("frame_grade_csv")
        self.label_input_teams = QtWidgets.QLabel(self.frame_grade_csv)
        self.label_input_teams.setGeometry(QtCore.QRect(0, 10, 171, 20))
        self.label_input_teams.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_teams.setObjectName("label_input_teams")
        self.button_input_teams = QtWidgets.QPushButton(self.frame_grade_csv)
        self.button_input_teams.setGeometry(QtCore.QRect(-3, 3, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.button_input_teams.setFont(font)
        self.button_input_teams.setFlat(True)
        self.button_input_teams.setObjectName("button_input_teams")
        self.button_input_teams.raise_()
        self.label_input_teams.raise_()
        self.gridLayout.addWidget(self.frame_grade_csv, 0, 0, 1, 1)
        self.button_process = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.button_process.setObjectName("button_process")
        self.gridLayout.addWidget(self.button_process, 2, 0, 1, 2)
        self.frame_student_xlsx = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame_student_xlsx.setAcceptDrops(True)
        self.frame_student_xlsx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_student_xlsx.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_student_xlsx.setObjectName("frame_student_xlsx")
        self.label_input_students = QtWidgets.QLabel(self.frame_student_xlsx)
        self.label_input_students.setGeometry(QtCore.QRect(6, 10, 161, 20))
        self.label_input_students.setAlignment(QtCore.Qt.AlignCenter)
        self.label_input_students.setObjectName("label_input_students")
        self.button_input_students = QtWidgets.QPushButton(self.frame_student_xlsx)
        self.button_input_students.setGeometry(QtCore.QRect(0, 0, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.button_input_students.setFont(font)
        self.button_input_students.setFlat(True)
        self.button_input_students.setObjectName("button_input_students")
        self.button_input_students.raise_()
        self.label_input_students.raise_()
        self.gridLayout.addWidget(self.frame_student_xlsx, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ID Matching"))
        self.label_output_xlsx.setText(_translate("MainWindow", "Output XLSX"))
        self.name_output_xlsx.setText(_translate("MainWindow", "(add a file from Teams first)"))
        self.label_input_teams.setText(_translate("MainWindow", "Teams CSV"))
        self.button_input_teams.setText(_translate("MainWindow", "(drag and drop, or click, to import)"))
        self.button_process.setText(_translate("MainWindow", "Output matched file"))
        self.label_input_students.setText(_translate("MainWindow", "Student Logins XLSX"))
        self.button_input_students.setText(_translate("MainWindow", "(drag and drop, or click, to import)"))
